from config import settings
#CLINETR SIDE ERROR 
LOGOUT_FAILED="Logout failed"
REFRESH_TOKEN_REQUIRED="Refresh token is required"
PASSWORD_NOT_PROVIDED_FOR_UPDATE="Password not provided"
PASSWORD_REGIX_ERROR = "Invalid password, please go through the password regex"
UPDATED_PASSWORD_ERROR="Updated password is same as the current password"
INVALID_CUSTOMER_ID="Invalid customer "
CUSTOMERNAME_IS_REQUIRED="Please select a name"
CUSTOMERNAME_MAX_LENGTH_ERROR = f"Customer name should not be more than {settings.CUSTOMERNAME_MAX_LENGTH_ERROR} characters"
CUSTOMERNAME_MIN_LENGTH_ERROR = f"Customer name should be at least {settings.CUSTOMERNAME_MIN_LENGTH_ERROR} characters"
EMAIL_IS_REQUIRED ="Email is required"
EMAIL_NOT_VALID= "Email is not valid"
EMAIL_ALREADY_EXISTS="Email is already exist"
MOBILE_NO_MAX_LENGTH_ERROR=f"Mobile number should not be more than {settings.MOBILE_NO_MAX_LENGTH_ERROR} digits"
MOBILE_NO_MIN_LENGTH_ERROR=f"Mobile number should be at least {settings.MOBILE_NO_MIN_LENGTH_ERROR} digits"
MOBILE_NO_NOT_DIGIT="Mobile number should only contain digits"
PASSWORD_MAX_LENGTH_ERROR=f"Password should not be more than {settings.PASSWORD_MAX_LENGTH_ERROR} characters"
PASSWORD_MIN_LENGTH_ERROR=f"Password should be at least {settings.PASSWORD_MIN_LENGTH_ERROR} characters"
PASSWORD_NOT_PROVIDED="Password is required"
PASSWORD_NOT_SECURE="Password must contain at least one lowercase letter, one uppercase letter, one digit, and one special character"
LOGIN_ID_OR_EMAIL_ID_NOT_PROVIDED = "Login ID or Email ID not provided"
PASSWORD_NOT_PROVIDED_FOR_LOGIN= "Please specify your password"
INVALID_CREDENTIALS="Invalid Credentials"   
USER_NOT_FOUND= "User not exist"
INVALID_BEAUTICIAN_ID="Invalid beautician"
INVALID_BEAUTICIAN_ID_DOES_NOT_EXIST="Invalid beautician,it has been removed or doesn't exist"
NAME_IS_REQUIRED="Please select a name"
BEAUTICIAN_NAME_MAX_LENGTH_ERROR=f"Beautician name cannot exceed {settings.BEAUTICIAN_NAME_MAX_LENGTH} characters"
BEAUTICIAN_NAME_MIN_LENGTH_ERROR=f"Beautician name should be at least {settings.BEAUTICIAN_NAME_MIN_LENGTH} characters"
USER_ID_NAME_NOT_PROVIDED="User name is required"
USER_ID_NAME_MAX_LENGTH_ERROR=f"User name cannot exceed {settings.USER_ID_NAME_MAX_LENGTH} characters"
USER_ID_NAME_MIN_LENGTH_ERROR=f"User name should be at least {settings.USER_ID_NAME_MIN_LENGTH} characters"
AADHAAR_NOT_PROVIDED="Aadhaar is required"
SPECIALIZATION_NOT_PROVIDED="Specialization is required"
EXPERIENCE_NOT_PROVIDED = "Experience is required"
INVALID_SORTING_ORDER="Invalid sorting order"
SORTING_ORDER_REQUIRED="Select a sorting order to have the user list"
USER_ID_IS_REQUIRED = "User is required"
USER_ID_DOES_NOT_EXIST = "Invalid user,it has been removed or doesn't exist"
#SUCCESS CLINET SIDE MESSAGE
LOGOUT_SUCCESSFUL="Logout successful"
ACCESS_TOKEN_GRANTED="Access token fetched successful"
PASSWORD_SUCCESSFULLY_CHANGED="Your password has been changed successfully"
PASSWORD_GENERATED_SUCCESSFULLY="Random password generated successfully"
USER_ADDED_SUCCESSFUL="User added successfully"
LOGIN_SUCCESSFUL="Login successfully"
USER_LIST_SUCCESSFULLY="User fetched successfully"
USER_DELETED_SUCCESSFULLY = "User deleted successfully"
VALIDATE_SUCCESSFUL ="Validate successful"
USER_UPDATED_SUCCESSFUL = "User updated successfully"

#SERVER ERROR 
INTERNAL_SERVER_ERROR="Something went wrong" 